In [2]:
"""Learn numpy basics 💯😂"""

import numpy as np


a = np.array([1, 2, 3], dtype=np.int16) # integer which takes 8 bits (2 bytes)
b = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 1024],
    ],
    dtype=np.int16,
)
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]], dtype=np.int8)

print(f"There are {c.size} total number of items")
print(f"Used bytes are: {c.nbytes}") # Each item is stored using 16 bits which is two bytes and we have 12 items in total
print(f"Matrix shpae is {c.shape}")
print(f"Number of dimensions are: {c.ndim}")

There are 8 total number of items
Used bytes are: 8
Matrix shpae is (2, 2, 2)
Number of dimensions are: 3


### Matrix Operations
1. Addition - should be the same size and addition is done element-wise.
2. Subtraction - both operands should be the same size and is done element wise
3. Division
4. Multiplication
    - Scalar
    - Dot product

In [3]:
v = np.array([7,0,1])
w = np.array([8,9,5])

print(np.add(v,w))
print(np.subtract(v,w))
print(np.divide(v, w))
print(np.multiply(2, v)) # scalar multiplication
print(np.multiply(v,w))

[15  9  6]
[-1 -9 -4]
[0.875 0.    0.2  ]
[14  0  2]
[56  0  5]


In [10]:
print("Adding to all elements ", a + 2)
print("Subtracting from ", a - 2)
print("Multiplying all elements ", a * 2)
print("Dividing all ", a / 2)
print("Dividing all ", a // 2)
print("Squaring all ", a ** 2)
print("Sin for all ", np.cos(a))
print("Cos all ", np.cos(a))
print("Tangent for all ", np.tanh(a))

Adding to all elements  [3 4 5]
Subtracting from  [-1  0  1]
Multiplying all elements  [2 4 6]
Dividing all  [0.5 1.  1.5]
Dividing all  [0 1 1]
Squaring all  [1 4 9]
Sin for all  [ 0.5403023 -0.4161468 -0.9899925]
Cos all  [ 0.5403023 -0.4161468 -0.9899925]
Tangent for all  [0.7615942 0.9640276 0.9950548]


### Indexing & Slicing
Syntax 
1. array[, ] Indexing (each dimension)
2. array[: , :] Slicing (each dimension)
    - The first one is for rows
    - The second one is for columns

In [79]:
b[1, 3] = 256    # If I want to change the value 8 in the second row to 256
b[0, 0] = 128    # Change the first element in the first row to 128
b[:2, :-2] = np.array([[0,1], [2,3]])      # In the first two rows, get the first two columns
print(b[:, :])

# c[:, :, :]
c[:,1,0]


[[   0    1    3    4]
 [   2    3    7  256]
 [   9   10   11 1024]]


array([3, 7], dtype=int8)

In [43]:
g = np.array([1,2,3,4,5,6,7,8,9,10])
# I want to get all evens
# index with a list
g[[1,3,5,7,9]]

array([ 2,  4,  6,  8, 10])

In [49]:
# boolean indexing
g[g % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [113]:
print(np.zeros((2,3)), "\n")
print(np.ones((2,3), np.int8), "\n")
print(np.full(
    shape=(2,3),
    fill_value=7,
    dtype='int8'
), "\n")
print(np.full_like(c, 10), "\n")
print(np.identity(2)) # all 1s are in a diagonal shape

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1 1 1]
 [1 1 1]] 

[[7 7 7]
 [7 7 7]] 

[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]] 

[[1. 0.]
 [0. 1.]]


In [111]:
np.random.randint(1, 5, (2,3)) # create an array, of shape (2,3) filled with random integers between 2 and 4 
np.random.rand(3,4)

array([[0.34874364, 0.67755809, 0.65588548, 0.73098985],
       [0.14554614, 0.06313625, 0.43839673, 0.54010759],
       [0.68592455, 0.21641082, 0.5816395 , 0.75286246]])

In [122]:
np.repeat([[7,8,9], [10,11,12]], 2, axis=0)

array([[ 7,  8,  9],
       [ 7,  8,  9],
       [10, 11, 12],
       [10, 11, 12]])

In [128]:
e = np.ones((5,5))
e[1:4, 1:4] = np.zeros((3,3))
e[2, 2] = 9
e

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Copying arrays

In [ ]:
v
z = v 

z[0] =100
print(v)
print(z)

[100   0   1]
[100   0   1]


In [137]:
new = z.copy()

new[0] = 77
print(v)
print(new)

[100   0   1]
[77  0  1]


Note
When copying arrays you should not use the assignmnet operator because what it does is assign the pointer to the array instead of the actual values therefore, in the newly created array, when you change some values, the original array is also changed because it references the same location.

Instead, you the `copy()` method.


## Linear Algebra

In [19]:
a = np.ones((2,3))
b = np.full((3,2), 2)
print(a, "\n")
print(b)
np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]] 

[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [18]:
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.float64(1.0)

In [22]:
print(np.min(a))
print(np.max(a, axis=0))
print(np.sum(a))

1.0
[1. 1. 1.]
6.0


In [36]:
d = np.array([[3,5,6], [9,0,6]])
print(d.astype(np.int8), '\n')
print(d.reshape((3,2)), '\n') # allocate values to the new shape row-by-row [avoid mismatch]
print(d.T, '\n') # the rows becomes columns

[[3 5 6]
 [9 0 6]] 

[[3 5]
 [6 9]
 [0 6]] 

[[3 9]
 [5 0]
 [6 6]] 



In [40]:
e = d == 9
e.astype(np.int8)

array([[0, 0, 0],
       [1, 0, 0]], dtype=int8)