# Learning Pytorch

In [43]:
import torch
import numpy as np
import warnings

from pprint import pprint

warnings.filterwarnings('ignore')
print(torch.__version__)

2.2.1+cpu


In [7]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
my_tensor = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ],
    dtype=torch.float32,
    device=device,
    requires_grad=True
)

print('the tensor is \n', my_tensor)
print(my_tensor.device) # assess the device in which this tensor is stored
print(my_tensor.shape) #  get the shape of the tensor (expecting a 2 by 3)
print(my_tensor.dtype) # get the data type of the tensor we just created
print(my_tensor.requires_grad) # parameter to see if the tensor requires gradient

the tensor is 
 tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
cpu
torch.Size([2, 3])
torch.float32
True


#### Note
This code creates a 2X3 PyTorch tesnsore with float32 data type, assigns it to a specified device which can eiher be cuda/gpu or cpu, and enables gradient checking for backprogragation. It is important to note that we initialized this tensor with the values we want it to hold. In contrast to this, there are many other methods of Tensor Initialization which are shown below:

- Empty Tensor: Creates an uninitialized tensor with random values
- Random Tensor: generates a random tensor with values between 0 and 1
- Zeros Tensor: creates a tensor filled with zeros
- Ones Tensor: creates a tensor filled with ones
- Arange Tensor: creates a 1 dimensional torch with values upto the specified value and moving on given step
- Linspace Tensor: generate a tensor with evenly separated values
- Normal Distributed Tensor: fills a tensor with values froma  normal or Gaussian distribution using given mean and standard deviation
- Uniform Distributed Tensor: fills a tensor with values from a uniform distribution between 0 and 1
- Diagonal Tensor: creates a tensor with ones in the diagonal line and zeros elsewhere


In [48]:
 # creates an empty tensor of size 3X3 with random values
empty =torch.empty(
    (3, 3),
    device=device,
    requires_grad=True,
    dtype=torch.float16
)

ones = torch.ones(
    (3,3),
    device=device,
    requires_grad=True,
    dtype=torch.float32,
)
zeros = torch.zeros(
    (3,3),
    dtype=torch.double,
    device=device,
    requires_grad=True,
)

x = torch.arange(
    start=0,
    end=5,
    step=1,
    dtype=torch.float64,
    device=device,
    requires_grad=True
)

y = torch.linspace(0.1, 1, 5)

identity = torch.eye(4,4)

normal = torch.empty(1,5).normal_(mean=0, std=1)

uniform = torch.empty(1,5).uniform_(0,1)

pprint(empty)
pprint(ones)
pprint(zeros)
print(x)
print(y)
print(identity)
print(normal)
print(uniform)

tensor([[ 4.8828e-03, -1.3000e+01,  6.9082e-05],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]], dtype=torch.float16,
       requires_grad=True)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64, requires_grad=True)
tensor([0., 1., 2., 3., 4.], dtype=torch.float64, requires_grad=True)
tensor([0.1000, 0.3250, 0.5500, 0.7750, 1.0000])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[ 7.5097e-01,  3.2400e-01, -4.6063e-04,  6.1590e-01, -5.8453e-01]])
tensor([[0.5854, 0.7050, 0.2377, 0.1417, 0.9635]])


In [ ]:
# DEMONSTRATING TYPE CONVERTION USING ONE TENSOR

tensor = torch.arange(5)
print("converting to Boolean", tensor.bool())
print("Short Tensor", tensor.short())
print("Long Tensor", tensor.long())
print("Half Tensor", tensor.half())
print("Convert to double ", tensor.double())
print("Convert to float ", tensor.float())

converting to Boolean tensor([False,  True,  True,  True,  True])
Short Tensor tensor([0, 1, 2, 3, 4], dtype=torch.int16)
Long Tensor tensor([0, 1, 2, 3, 4])
Half Tensor tensor([0., 1., 2., 3., 4.], dtype=torch.float16)
Convert to double  tensor([0., 1., 2., 3., 4.], dtype=torch.float64)
Convert to float  tensor([0., 1., 2., 3., 4.])


In [ ]:
# CONVERTING BETWEEN NUMPY AND TENSORS
    # it is not possible to call numpy() on tensor that requires gradient

np_zeros = np.zeros((5, 5))
to_tensor = torch.from_numpy(np_zeros) # convert np array to tensors
print(to_tensor)
to_tensor.numpy() # convert to numpy

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])